### ISSUE TITLE
Unable to load file

### ISSUE THREAD

**Issue by piranna** [shakiba/svgexport#5]
Trying to convert a image it give me the next error:

```bash
[piranna@Latitude:~/ShareIt Project/shareit-project_pfc]
 (master) > node_modules/.bin/svgexport "/home/piranna/ShareIt Project/shareit-project_pfc/_book/img/logo.svg" prueba
Error: Unable to load file (fail): /home/piranna/ShareIt,Project/shareit-project_pfc/_book/img/logo.svg
```

I've checked this manually since gitbook 2.0.0 was giving me failure, and seems to be a svgexport problem. The image source code is:

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="912.92645"
   height="324.69269"
   viewBox="-141 -12 507.81617 175.25288"
   id="svg2"
   version="1.1"
   inkscape:version="0.48.3.1 r9886"
   sodipodi:docname="logo.svg">
  <metadata
     id="metadata138">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title />
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <defs
     id="defs136" />
  <sodipodi:namedview
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1"
     objecttolerance="10"
     gridtolerance="10"
     guidetolerance="10"
     inkscape:pageopacity="0"
     inkscape:pageshadow="2"
     inkscape:window-width="960"
     inkscape:window-height="1032"
     id="namedview134"
     showgrid="false"
     inkscape:zoom="1"
     inkscape:cx="460.78003"
     inkscape:cy="222.63388"
     inkscape:window-x="0"
     inkscape:window-y="24"
     inkscape:window-maximized="0"
     inkscape:current-layer="svg2"
     fit-margin-top="0"
     fit-margin-left="0"
     fit-margin-right="0"
     fit-margin-bottom="0" />
  <g
     id="background"
     transform="translate(-121.30226,5.834101)">
    <path
       inkscape:connector-curvature="0"
       id="background S"
       d="m 38.5,-18.78125 c -35.1780861,-1.204013 -63.298673,39.232929 -50.78125,71.9375 7.0685592,22.218168 29.871531,35.696466 51.875,38.21875 -0.363184,7.687349 -11.276037,10.77819 -16.648768,5.749076 -7.728489,-4.40416 -17.9199099,-3.780505 -24.351232,2.719674 -7.0675963,6.761 -14.428033,14.4547 -17.5,23.96875 -2.747432,9.73488 1.82978,20.88617 11.0625,25.28125 C 26.880658,172.82802 81.936894,155.68678 95.5625,115.5 107.54552,86.271537 94.416554,47.428637 64.15625,35.5 71.89496,26.017982 78.93943,15.712858 86.59375,6.03125 75.271522,-8.6628692 57.542311,-19.435053 38.5,-18.78125 z"
       style="fill:#ff0000;stroke:none" />
    <path
       inkscape:connector-curvature="0"
       id="background h"
       d="M 81.4375,-20.125 C 67.851885,-19.160615 60.775221,-3.0018632 64.09375,9.03125 63.915009,57.843523 64.034945,106.65626 64,155.46875 c 16.05666,9.88924 37.76441,4.09978 49.875,-9.28125 12.03202,13.61296 33.30302,18.05111 49.875,10.34375 0.43438,-23.67476 3.71549,-50.37763 -10.8125,-70.78125 -7.14839,-10.158173 -17.66258,-17.727776 -29.21875,-22.1875 -0.42602,-21.746056 4.12963,-45.42808 -6.40625,-65.4375 -7.83632,-11.618178 -21.799088,-18.964327 -35.875,-18.25 z"
       style="fill:#ff0000;stroke:none" />
    <path
       inkscape:connector-curvature="0"
       id="background a"
       d="m 184.3125,40.03125 c -37.84707,0.790967 -67.26462,44.621754 -53.125,79.90625 10.16822,31.35282 49.33619,48.92759 79.375,35.78125 11.42945,6.31336 25.22158,4.73679 37.4375,1.8125 0,-39.17708 0,-78.354167 0,-117.53125 -21.22918,-0.0054 -42.45833,0.003 -63.6875,0.03125 z"
       style="fill:#ff0000;stroke:none" />
    <path
       inkscape:connector-curvature="0"
       id="background r"
       d="M 232.125,39.53125 C 217.12466,41.002934 208.18,58.423442 212,72.21875 c 0,27.6875 0,55.375 0,83.0625 20.04857,12.52462 47.98477,0.50067 57.09375,-20.0625 5.38577,-10.01032 2.75086,-21.57302 2.65625,-32.25 0.0955,-4.110177 4.45086,-3.544742 7.28125,-2.875 4.18568,0.24223 10.64763,1.08867 12.96875,-2.375 0,-18.0625 0,-36.125 0,-54.1875 -14.19574,-7.001438 -30.46894,-1.004388 -45.40571,-3.810981 -4.82087,0.147954 -9.6919,0.570822 -14.46929,-0.189019 z"
       style="fill:#ff0000;stroke:none" />
    <path
       inkscape:connector-curvature="0"
       id="background e"
       d="M 305.34375,30.25 C 275.6128,29.569578 251.00681,60.086808 256,88.96875 c -2.03166,21.1008 0.77064,45.86929 18.625,59.6875 14.14503,12.51658 38.76317,16.06504 53,1.84375 7.64259,-8.08142 9.71746,-20.01881 8.71875,-30.625 C 360.94419,102.15705 362.47978,60.449106 338,41.96875 328.95407,34.31707 317.26322,29.786559 305.34375,30.25 z"
       style="fill:#ff0000;stroke:none" />
    <path
       inkscape:connector-curvature="0"
       id="background I"
       d="m 300,-18 c 0,19.3333333 0,38.666667 0,58 6.66667,0 13.33333,0 20,0 0,20 0,40 0,60 -6.66667,0 -13.33333,0 -20,0 0,20 0,40 0,60 33.33333,0 66.66667,0 100,0 0,-20 0,-40 0,-60 -6.66667,0 -13.33333,0 -20,0 0,-20 0,-40 0,-60 6.66667,0 13.33333,0 20,0 0,-20 0,-40 0,-60 -33.33333,0 -66.66667,0 -100,0 l 0,1 0,1 z"
       style="fill:#ff0000;stroke:none" />
    <path
       inkscape:connector-curvature="0"
       id="background t"
       d="m 364,-14 c 0.0628,6.0007284 -0.12485,11.9997088 -0.125,18 -6.625,0 -13.25,0 -19.875,0 0,19.65625 0,39.3125 0,58.96875 6.5823,2.217243 13.58533,0.368523 20.34375,1.0625 0.11099,24.00349 -4.25689,50.17981 7.28125,72.1875 12.52888,20.08487 40.13343,29.8601 62.375,20.4375 -0.0422,-26.76053 0.16005,-53.5242 -0.375,-80.28125 -3.33194,2.542092 -6.71756,5.003654 -9.65625,7.96875 0.0352,-6.781164 0.11528,-13.562298 0.0937,-20.34375 6.64583,0 13.29167,0 19.9375,0 0,-20 0,-40 0,-60 -6.66667,0 -13.33333,0 -20,0 0,-6.6666667 0,-13.3333333 0,-20 -20,0 -40,0 -60,0 l 0,1 0,1 z"
       style="fill:#ff0000;stroke:none" />
    <path
       inkscape:connector-curvature="0"
       id="background !"
       d="m 448.34375,80 c -24.4423,-1.727441 -43.89701,24.09276 -40.03125,47.3125 2.65088,16.82029 17.34211,30.62798 34.40625,32 17.62856,2.52438 36.81111,-7.11675 42.90625,-24.28125 C 495.2523,110.68022 475.76837,78.291293 448.34375,80 z"
       style="fill:#ff0000;stroke:none" />
  </g>
  <g
     id="outline"
     transform="translate(-121.30226,5.834101)">
    <path
       inkscape:connector-curvature="0"
       id="outline S"
       d="M 37.84375,-2.75 C 14.346874,-2.694129 -4.5117759,22.696931 2.25,45.25 c 4.1909782,17.870263 22.465292,30.008217 40.46875,29 10.844913,1.849591 16.578505,15.364375 11.375,24.8125 -5.547408,14.98502 -26.810321,22.12547 -39.3125,11.53125 -6.4710771,-2.24712 -9.436517,6.15481 -12.46875,10.125 -3.01870031,3.09263 -9.9975548,9.44034 -3.84375,13.09375 22.355258,17.27456 58.249927,11.825 74.65625,-11.09375 13.970927,-17.75015 15.078916,-46.104269 -1.40625,-62.6875 -9.260517,-10.207045 -23.186401,-14.059813 -36.5,-14.8125 -8.541349,-3.105902 -8.025928,-18.103953 1.53125,-19.75 4.451249,-1.105431 8.962046,1.017668 12.03125,4.1875 C 54.318207,22.145483 59.961104,14.712892 65.5625,7.25 57.978354,0.56783926 48.007987,-3.1657934 37.84375,-2.75 z"
       style="fill:#000000;stroke:none" />
    <path
       inkscape:connector-curvature="0"
       id="outline h"
       d="M 81.9375,-4.125 C 77.699006,-2.2286375 81.108057,7.0725533 80,12 c 0,44.010417 0,88.02083 0,132.03125 15.532512,2.34178 30.0262,-12.35328 28.15625,-27.75 0.43396,-3.88425 -0.94317,-7.89092 -0.15625,-11.6875 8.75073,2.15028 12.87164,11.75754 12.53125,20.125 2.41218,12.28999 15.17829,20.82866 27.46875,19.34375 0.0971,-17.37899 2.36618,-37.40055 -10.03125,-51.40625 C 130.66904,83.624725 119.64708,77.518964 108,76.28125 107.51694,55.582249 108.99441,34.732657 107.21875,14.125 104.37419,3.1287849 93.220135,-4.7511608 81.9375,-4.125 z"
       style="fill:#000000;stroke:none" />
    <path
       inkscape:connector-curvature="0"
       id="outline a"
       d="m 186.90625,56.03125 c -24.97465,-0.279744 -46.53119,24.735374 -42.625,49.5625 2.57982,24.47247 28.49397,43.30432 52.59375,37.5625 5.36287,-0.81116 10.52592,-4.35321 15.25,-5.4375 5.3206,4.85041 12.74123,6.96837 19.875,6.25 0,-29.32292 0,-58.645833 0,-87.96875 -9.52083,0 -19.04167,0 -28.5625,0 2.30781,4.563056 -0.43513,2.686973 -3.0625,1.78125 -4.35547,-1.268397 -8.91675,-1.920248 -13.46875,-1.75 z m 1.71875,27.9375 c 12.80205,-0.188561 20.49613,17.47062 11.46875,26.625 -7.62309,9.38346 -25.12481,5.68276 -27.625,-6.53125 -2.81809,-9.830683 5.78241,-20.902887 16.15625,-20.09375 z"
       style="fill:#000000;stroke:none" />
    <path
       inkscape:connector-curvature="0"
       id="outline r"
       d="m 234.21875,55.5 c -6.89055,0.357292 -7.35409,8.493014 -6.21875,13.65625 0,24.9375 0,49.875 0,74.8125 15.59463,2.46701 30.30495,-12.45848 28.03125,-27.96875 0.0905,-9.98229 -2.49441,-23.700688 7.90625,-29.625 3.57202,-2.239584 7.92772,-2.631656 12.0625,-2.4375 0,-9.270833 0,-18.541667 0,-27.8125 -6.91356,-0.611424 -14.23274,0.06891 -20.5,2.28125 -4.03959,-5.710874 -12.06288,-0.499047 -17.65625,-2.6875 -1.18866,-0.246841 -2.41259,-0.301353 -3.625,-0.21875 z"
       style="fill:#000000;stroke:none" />
    <path
       inkscape:connector-curvature="0"
       id="outline e"
       d="m 304.625,46.28125 c -19.83755,0.06335 -35.77622,20.195601 -32.5,39.59375 0.11183,15.52035 -3.17363,33.86406 8.5,46.25 7.70531,8.68876 20.96967,14.87319 32.375,9.9375 7.21118,-3.97473 7.57141,-13.14635 7.3125,-20.34375 0.99807,-5.81239 -6.41294,-6.75587 -10.53125,-5.6875 -2.69511,0.23524 -5.7975,0.23412 -7.875,-1.78125 16.33818,1.10672 33.30503,-9.47626 36.875,-25.90625 4.58817,-17.502817 -6.93771,-37.316259 -24.75,-41.09375 -3.05862,-0.783851 -6.23965,-1.104025 -9.40625,-0.96875 z m 1.59375,27.78125 c 6.34272,-0.210713 7.80265,10.795517 1.09375,11.71875 -2.7885,0.04966 -8.82868,1.972282 -7.46875,-2.75 -0.19208,-4.262542 1.18958,-9.039184 6.375,-8.96875 z"
       style="fill:#000000;stroke:none" />
    <path
       inkscape:connector-curvature="0"
       id="outline I"
       d="m 316,-2 c 0,8.6666667 0,17.333333 0,26 6.66667,0 13.33333,0 20,0 0,30.666667 0,61.333333 0,92 -6.66667,0 -13.33333,0 -20,0 0,9.33333 0,18.66667 0,28 22.66667,0 45.33333,0 68,0 0,-9.33333 0,-18.66667 0,-28 -6.66667,0 -13.33333,0 -20,0 0,-30.666667 0,-61.333333 0,-92 6.66667,0 13.33333,0 20,0 0,-9.333333 0,-18.6666667 0,-28 -22.66667,0 -45.33333,0 -68,0 l 0,1 0,1 z"
       style="fill:#000000;stroke:none" />
    <path
       inkscape:connector-curvature="0"
       id="outline t"
       d="m 380,2 c -0.59202,5.9836638 0.86251,12.096416 -0.3125,18 -6.5625,0 -13.125,0 -19.6875,0 0,9.333333 0,18.666667 0,28 6.66667,0 13.33333,0 20,0 0.43452,22.866464 -0.95044,45.872025 0.75,68.65625 3.35704,16.6594 20.2879,29.10827 37.25,27.34375 0,-9.36458 0,-18.72917 0,-28.09375 -5.58507,2.08028 -11.73476,-3.24994 -10,-9.03125 0,-19.625 0,-39.25 0,-58.875 6.66667,0 13.33333,0 20,0 0,-9.333333 0,-18.666667 0,-28 -6.66667,0 -13.33333,0 -20,0 0,-6.666667 0,-13.3333333 0,-20 -9.33333,0 -18.66667,0 -28,0 l 0,1 0,1 z"
       style="fill:#000000;stroke:none" />
    <g
       id="outline !">
      <path
         style="fill:#000000;stroke:none"
         d="M 446.84375,96.03125 C 430.16443,95.970453 418.35993,116.45564 426.5625,131 c 6.76074,14.22265 28.40934,17.56319 38.90625,5.59375 11.44667,-11.30162 6.96978,-33.55639 -8.40625,-38.8125 -3.20926,-1.317284 -6.70915,-1.969529 -10.21875,-1.75 z"
         id="path4047"
         inkscape:connector-curvature="0" />
      <path
         style="fill:#000000;stroke:none"
         d="M 423.78125,-11.8125 C 427.32383,24.123872 430.82327,60.064562 434.375,96 c 9.08333,0 18.16667,0 27.25,0 3.64047,-36.663052 7.21281,-73.332909 10.8125,-110 -16.29167,0 -32.58333,0 -48.875,0 0.0729,0.729167 0.14583,1.458333 0.21875,2.1875 z"
         id="path4049"
         inkscape:connector-curvature="0" />
    </g>
  </g>
  <g
     id="text"
     transform="translate(-121.30226,5.834101)">
    <path
       sodipodi:nodetypes="ccsscscsssccssscscsssc"
       inkscape:connector-curvature="0"
       id="text S"
       d="m 0,130 12,-16 c 4.467466,3.17047 9.805608,5.10081 15.267621,5.52097 5.462014,0.42016 11.032585,-0.67104 15.932391,-3.12095 C 52.999625,111.50022 59.711793,100.95251 60,90 59.873164,84.799746 57.678227,79.678229 53.999999,76.000001 50.321771,72.321773 45.200254,70.126836 40,70 29.103241,70.184963 18.25423,64.8371 11.764522,56.081718 5.2748146,47.326337 3.3131165,35.391041 6.6589327,25.019011 10.004749,14.64698 18.571107,6.107831 28.953741,2.7951407 39.336375,-0.51754957 51.265379,1.4823337 60,8 L 48,24 c -3.690031,-2.745543 -8.734303,-3.568305 -13.105496,-2.137608 -4.371194,1.430696 -7.952803,5.076719 -9.305416,9.472712 -1.352614,4.395993 -0.440182,9.424797 2.37063,13.065341 C 30.77053,48.04099 35.404804,50.196243 40,50 50.400507,50.253673 60.643542,54.643545 67.999998,62.000002 75.356455,69.356458 79.746327,79.599493 80,90 c 0.02627,9.236805 -2.574482,18.46669 -7.419399,26.33091 -4.844917,7.86423 -11.918899,14.33829 -20.180582,18.46913 -8.261683,4.13084 -17.685319,5.90559 -26.883649,5.06299 C 16.31804,139.02043 7.3736816,135.5631 0,130"
       style="fill:#ff7f2a;stroke:none" />
    <path
       sodipodi:nodetypes="cscsccsccsccscc"
       inkscape:connector-curvature="0"
       id="text h"
       d="m 104,100 c 5.20025,0.12684 10.32177,2.32177 14,6 3.67823,3.67823 5.87316,8.79975 6,14 0.12684,5.20025 2.32177,10.32177 6,14 3.67823,3.67823 8.79975,5.87316 14,6 l 0,-20 C 143.74633,109.59949 139.35645,99.356458 132,92.000002 124.64354,84.643545 114.40051,80.253673 104,80 l 0,-60 C 103.87316,14.799746 101.67823,9.6782291 97.999999,6.0000009 94.321771,2.3217727 89.200254,0.12683626 84,0 l 0,140 c 5.200254,-0.12684 10.321771,-2.32177 13.999999,-6 3.678231,-3.67823 5.873161,-8.79975 6.000001,-14 l 0,-20"
       style="fill:#ff7f2a;stroke:none" />
    <path
       inkscape:connector-curvature="0"
       id="text a"
       d="m 188.00503,60.007699 c -22.09139,0 -39.99792,17.906529 -39.99792,39.997921 0,22.09138 17.90653,39.99791 39.99792,39.99791 9.08121,0 17.44802,-3.03614 24.16215,-8.13517 0.56359,0.74952 1.16162,1.47451 1.8252,2.13809 3.67823,3.67823 8.81032,5.87024 14.01057,5.99708 l 0,-39.99791 0,-39.997921 -20.00765,0 0,5.353915 c -5.88304,-3.402721 -12.70531,-5.353915 -19.99027,-5.353915 z m 0,19.990267 c 11.0457,0 19.99027,8.961953 19.99027,20.007654 0,11.04569 -8.94457,19.99026 -19.99027,19.99026 -11.0457,0 -20.00765,-8.94457 -20.00765,-19.99026 0,-11.045701 8.96195,-20.007654 20.00765,-20.007654 z"
       style="fill:#ff7f2a;stroke:none" />
    <path
       inkscape:connector-curvature="0"
       id="text r"
       d="m 269.99989,59.938167 c -6.24524,-0.03132 -12.46608,1.553253 -17.99124,4.46739 l 0,-4.397858 -20.00765,0 0,35.756503 c -0.079,1.409713 -0.0852,2.830539 0,4.241418 l 0,39.99791 c 5.20025,-0.12684 10.31496,-2.31885 13.99319,-5.99708 3.67823,-3.67823 5.88762,-8.81032 6.01446,-14.01057 l 0,-19.99026 c 0.12684,-5.200261 2.31885,-10.332348 5.99708,-14.010574 3.67823,-3.678226 8.79294,-5.870244 13.99319,-5.99708 l 0,-19.990267 c -0.66463,-0.04011 -1.3337,-0.06619 -1.99903,-0.06953 z"
       style="fill:#ff7f2a;stroke:none" />
    <path
       inkscape:connector-curvature="0"
       id="text e"
       d="m 306.27788,50.255925 c -4.02462,-0.04962 -8.06316,0.709682 -11.78557,2.242386 -5.41441,2.229387 -10.13373,6.092689 -13.40217,10.95119 -3.26844,4.858501 -5.06867,10.692928 -5.09317,16.548465 l 0,30.002784 c 0.19024,7.80038 3.48696,15.48113 9.00431,20.99847 5.51734,5.51735 13.1981,8.81407 20.99847,9.00431 2.60013,-0.0634 5.16618,-1.16811 7.00529,-3.00723 1.83912,-1.83911 2.92645,-4.38777 2.98985,-6.9879 l 0,-10.01252 -9.99514,0 c -2.60012,-0.0634 -5.16617,-1.15072 -7.00528,-2.98985 -1.83912,-1.83911 -2.92645,-4.40515 -2.98985,-7.00528 l 9.99513,0 c 5.85555,-0.0245 11.68997,-1.82473 16.54847,-5.09317 4.8585,-3.26844 8.72181,-7.987755 10.95119,-13.402174 2.22939,-5.414418 2.81731,-11.502095 1.66875,-17.243778 -1.14857,-5.741683 -4.02942,-11.121625 -8.16993,-15.262134 -4.14051,-4.140509 -9.52046,-7.021372 -15.26214,-8.169935 -1.79427,-0.358927 -3.62883,-0.551078 -5.45821,-0.573634 z m -0.55625,19.868587 c 2.67671,-0.03388 5.38568,0.970441 7.28341,2.868169 2.76033,2.760334 3.64172,7.237286 2.15547,10.846893 -1.48625,3.609606 -5.25708,6.137194 -9.16076,6.153525 l -9.99513,0 0,-9.995133 c 0.0163,-3.903686 2.54393,-7.674505 6.15353,-9.160757 1.128,-0.464453 2.34679,-0.6973 3.56348,-0.712697 z"
       style="fill:#ff7f2a;stroke:none" />
    <path
       id="text I"
       d="m 340,20 -20,0 0,-20 60,0 0,20 -20,0 0,100 20,0 0,20 -60,0 0,-20 20,0 z"
       style="fill:#ff7f2a;stroke:none"
       inkscape:connector-curvature="0" />
    <path
       sodipodi:nodetypes="csccccccccccccscc"
       inkscape:connector-curvature="0"
       id="text t"
       d="m 414,140 c -7.80038,-0.19024 -15.48267,-3.48264 -21.00001,-8.99999 C 387.48264,125.48267 384.19024,117.80038 384,110 l 0,-66 -20,0 0,-20 20,0 0,-20 20,0 0,20 20,0 0,20 -20,0 0,66 c 0.0634,2.60013 1.16087,5.1609 2.99999,7.00001 1.83911,1.83912 4.39988,2.93658 7.00001,2.99999 l 0,20"
       style="fill:#ff7f2a;stroke:none" />
    <g
       id="text !"
       style="fill:#ffffff">
      <path
         id="ellipse130"
         d="m 468,120 c 0,11.04569 -8.95431,20 -20,20 -11.04569,0 -20,-8.95431 -20,-20 0,-11.04569 8.95431,-20 20,-20 11.04569,0 20,8.95431 20,20 z"
         style="fill:#ffffff;stroke:none"
         inkscape:connector-curvature="0" />
      <path
         id="polygon132"
         d="m 438,92 -10,-102 40,0 -10,102 z"
         style="fill:#ffffff;stroke:none"
         inkscape:connector-curvature="0" />
    </g>
  </g>
</svg>
```

**Comment by shakiba** [comment]
There is a space in file path (`/ShareIt Project/`) which causes this issue, I will check if I can fix it, but meanwhile you can remove that space from file path.

**Comment by shakiba** [comment]
I have fixed the issue for spaces in files which are passed in directly from command line, which is the case here. Please install the new release (0.2.1) and try it.

**Comment by piranna** [comment]
I've tryied version 0.2.1 and the space in the path issue is fixed, thank you! :-) Seems it's a dependency of ```gitbook``` but it's not working there, maybe I'll need to open an issue there...

**Comment by shakiba** [comment]
You are welcome, thank you for reporting! Yes, you can notify them about this issue/update, I hope they update to new version soon.

**Comment by SamyPesse** [comment]
svgexport is not a dependency of gitbook, it only shows a message to install it globally if not installed.

So you just need to update svgexport in your system.

**Comment by piranna** [comment]
> svgexport is not a dependency of gitbook, it only shows a message to install it globally if not installed.

I have ```svgexport``` in my book ```package.json``` file so it's automatically installed "locally". Could this be the problem?

**Comment by SamyPesse** [comment]
Yes probably, npm is maybe doing more priority to the local version of svgexport. Remove it from your local folder and install it globally: `npm install svgexport -g`

**Comment by piranna** [comment]
I've just test it (remove local, install global) and gitbook is still not working, but launching ```svgexport``` manually works:

```bash
[piranna@Latitude:~/ShareIt Project/shareit-project_pfc]
 (master) > svgexport "/home/piranna/ShareIt Project/shareit-project_pfc/_book/img/logo.svg" prueba
/home/piranna/ShareIt Project/shareit-project_pfc/_book/img/logo.svg /home/piranna/ShareIt Project/shareit-project_pfc/prueba png 100% 1x 0:0:912.92:324.69 912.92:324.69

[piranna@Latitude:~/ShareIt Project/shareit-project_pfc]
 (master) > file prueba 
prueba: PNG image data, 913 x 325, 8-bit/color RGBA, non-interlaced

[piranna@Latitude:~/ShareIt Project/shareit-project_pfc]
 (master) > file "/home/piranna/ShareIt Project/shareit-project_pfc/_book/img/logo.svg"
/home/piranna/ShareIt Project/shareit-project_pfc/_book/img/logo.svg: SVG Scalable Vector Graphics image
```

**Comment by SamyPesse** [comment]
Ok I've found the problem: https://github.com/GitbookIO/gitbook/blob/version/2.0/lib/utils/images.js#L18

I'll fix it for the next release.

**Comment by SamyPesse** [comment]
I fixed it in GitBook!

**Comment by shakiba** [comment]
@SamyPesse I suggest following code instead:
```js
require('svgexport').render({ input: source, output: dest }, function(err){ });
```

**Comment by piranna** [comment]
:+1: By the way, ```gitbook-plugin-autocover``` use internally ```node-canvas```, that has fewer dependencies that ```phantomjs``` and it's doing the same thing (convert SVG to PNG, in that case for the cover), why it's that being used instead?

Disclaimer: I'm the one that added SVG support on ```gitbook-plugin-autocover```... :-P

**Comment by shakiba** [comment]
And to avoid spaces:
```js
require('svgexport').render({ input: [source], output: [[dest]] }, function(err){ });
```

**Comment by piranna** [comment]
+1 to use ```svgexport``` as a require() module instead of external command.

**Comment by shakiba** [comment]
@piranna Regarding dependencies, `node-canvas` needs Cairo to already be installed, so it doesn't have fewer dependencies than `phantomjs`.

**Comment by SamyPesse** [comment]
I'll take a look at using `svgexport` as a require module, but I think from a process point of view, it's better to run this in another process and avoid running everything in the same node event loop.
The perfect solution will be a `svgexport` service that runs in the background and convert images (avoid starting the process each time but still having another process).

`node-canvas` depends on Cairo (not easy to install), and doesn't render all svgs just like browsers do.

**Comment by shakiba** [comment]
phantomjs already is executed in another process, svgexport only prepares your commands and sends them to phantomjs, actually to nodejs wrapper for phantomjs, phantomjs has it's own engine and does not use nodejs. Keeping phantomjs running in another process is an interesting idea, I have considered it before but didn't have enough time to implement it, some phantomjs wrappers do similar thing.

**Comment by piranna** [comment]
> I'll take a look at using svgexport as a require module, but I think from a process point of view, it's better to run this in another process and avoid running everything in the same node event loop.

Maybe an objects stream, being each object an input SVG file and the output an object stream of PNG files? When you finish processing, just close the stream and PhantomJS can close...


> node-canvas depends on Cairo (not easy to install), and doesn't render all svgs just like browsers do.

I know it depends on Cairo, and I think PhantomJS too... only thing that I feel node-canvas is less bloated on system resources dependencies. On the other hand it's true browsers rendering support is fairly superior, so this could be a good reason to use it...

**Comment by shakiba** [comment]
> I know it depends on Cairo, and I think PhantomJS too... only thing that I feel node-canvas is less bloated on system resources dependencies.

Phantomjs is only installed locally and ships inside a cross-platform npm package while as far as I know node-canvas requires you to install Cairo in your system. I'm open to evaluate any other option to use instead of phantomjs if it can be installed just as a npm package without any external dependency.

**Comment by shakiba** [comment]
@SamyPesse As I was browsing your code to see how you have used svgeport, I found [this script](https://github.com/GitbookIO/logos/blob/master/convert.sh) where you use `convert` to pad an exported image. I just released a new update which supports padding, now you can just run:
```
svgexport ./src/gitbook-text.svg ./pngs/320-text.png pad 320:132
```

**Comment by piranna** [comment]
I've updated the ```gitbook``` dependency to that commit and the error is still there. The code is the new one, but although I put some traces they are being ignored. Seems that module is not being used, and instead the old code is being used, but don't know why or where it's located, since ```gitbook-cli``` don't include it... :-/

**Comment by shakiba** [comment]
> but don't know why or where it's located

Try this: `sudo updatedb; locate svgexport/package.json`

**Comment by SamyPesse** [comment]
To use the latest commit from `GitBook/gitbook` with `gitbook-cli`:

```
$ git clone -b version/2.0 https://github.com/GitbookIO/gitbook.git ./gitbook
$ gitbook versions:link 2.0.0 ./gitbook
```

Now the version `2.0.0` wil be associated with the `./gitbook` folder.

You can uninstall it using: `gitbook versions:uninstall 2.0.0`

**Comment by piranna** [comment]
> To use the latest commit from GitBook/gitbook with gitbook-cli:
>
> $ git clone -b version/2.0 https://github.com/GitbookIO/gitbook.git ./gitbook
> $ gitbook versions:link 2.0.0 ./gitbook
>
> Now the version 2.0.0 wil be associated with the ./gitbook folder.

Ok, now I got it to work, though gitbook-cli would be like grunt-cli,
that use the grunt package installed in each project, but instead it's
defined on the book.json file. It finish correctly but I'm not getting
the output PDF file but probably I'm doing something wrong, I'll
review it later.


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by piranna** [comment]
I've just updated to ```gitbook-cli``` v0.3.4 and ```gitbook``` v2.1.0 and it's still showing the message about need to install ```svgexport```. Since PhantomJS run on it's own process, could this be fixed @SamyPesse? As a workaround I've done ```npm install --save-dev svgexport``` and it worked, although now I get another error regarding certificates:

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Hostname/IP doesn't match certificate's altnames: "Host: www.gitbook.io. is not in the cert's altnames: DNS:*.gitbook.com, DNS:gitbook.com"
    at Object.checkServerIdentity (tls.js:210:15)
    at TLSSocket.<anonymous> (_tls_wrap.js:934:31)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)
```

**Comment by SamyPesse** [comment]
Where are you usingthe gitbook.io domain name ? you should switch to gitbook.com.

**Comment by piranna** [comment]
You are right, I had some links on the README.md file to give credits to GitBook, sorry :-P But, how it's possible that a markdown file could give this problem?

**Comment by SamyPesse** [comment]
This is not the markdown links but the images (you probably had the gitbook badge with a `gitbook.io` domain name), since the image is an SVG, GitBook try to download it to convert it to PNG; but the download failed.

**Comment by piranna** [comment]
Exactly, it was the GitBook badge :-P Thank you very much! :-D
